Siw 1242 writing readme files
pagopa/io-wallet pull request #257
Opened 2024-10-25 08:14 UTC by christianatzeni

This PR consists in the `README.md` files enhancement. I've updated all the `README.md` file present in the monorepo:
- `README.md` of `io-wallet-support-func` project.
- `README.md` of `io-wallet-user-func` project.
- `README.md` of `io-wallet-common` package..
- `README.md` of `io-wallet` monorepo.

Since `README` files are the first doc that any resource (old or new) reads, I focused on a minimal and essential approach: I have included commands for the usability of the monorepo, without exhaustive and rigorous explanations (there are official documentations for those).

The related task is [SIW-1242](https://pagopa.atlassian.net/browse/SIW-1242).

#### List of Changes

- Updated the `README.md` file of `io-wallet-support-func` (project)
- Updated the `README.md` file of `io-wallet-user-func` (project)
- Updated the `README.md` file of `io-wallet-common` (package)
- Updated the `README.md` file of `io-wallet` (monorepo)

#### Motivation and Context

Make it clear to any new resource the way, purposes and scope of the different projects/packages present in the monorepo. Provide a kind of "tutorial" ready to use, minimal and essential, to facilitate the new resource and allow it to easily use the various services locally.

#### How Has This Been Tested?

Since these are just README.md files, in my opinion the best way to test changes is to experiment directly in the field and see how a new resource "works" by reading those READMEs.

#### Screenshots (if appropriate):

#### Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-10-25 13:34 UTC, silvicir requested changes

2024-10-25 13:34 UTC, silvicir commented on host.json
I think this is an oversight

2024-10-25 13:34 UTC, silvicir commented on README.md
I would remove the last two sentences, as 'simple' and 'complex' are subjective adjectives

2024-10-25 13:34 UTC, silvicir commented on README.md
> +It's strongly recommended to start looking at the code and understanding how Azure functions work from the `io-wallet-support-func` project, even just to have a basic overview. The `io-wallet` monore
I would suggest deleting the first sentence, as it may be subjective

2024-10-25 13:34 UTC, silvicir commented on README.md
> +It is recommended that you read the README.md files of both projects only after reading the current README. In according to this monorepo, in this codepase you can find the `io-wallet.code-workspace`
The `io-wallet.code-workspace` is a vscode configuration file

2024-10-25 13:34 UTC, silvicir commented on README.md
> +This project uses [Yarn](https://classic.yarnpkg.com/) as depndencies manager and [Turborepo](https://turbo.build/repo/docs) as monorepo manager. Before continuing to read, it is strongly recommended
there is a typo: "dependencies"

2024-10-25 15:45 UTC, gunzip requested changes

2024-11-07 15:54 UTC, silvicir commented
the file should include instructions on how to start the project so that anyone can get it run even without prior knowledge of it. So you should include all the `az login` steps (as in the Confluence document I showed you)

2024-12-16 15:04 UTC, silvicir approved these changes

2024-12-16 15:05 UTC, merged